resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

files {
	'data/ai/loadouts.meta',
	'data/ai/vehiclelayouts.meta',
	'data/ai/vehiclelayouts_menacer.meta',
	'data/ai/vehicleweapons_hacker.meta',
	'data/ai/vehicleweapons_menacer.meta',
	'data/ai/vehicleweapons_mule4.meta',
	'data/ai/vehicleweapons_oppressor2.meta',
	'data/ai/vehicleweapons_pounder2.meta',
	'data/ai/vehicleweapons_scramjet.meta',
	'data/ai/vehicleweapons_speedo4.meta',
	'data/ai/vehicleweapons_strikeforce.meta',
	'data/ai/weaponanimations.meta',
	'data/ai/weaponstonehatchet.meta',
	'data/anim/clip_sets/clip_sets.xml',
	'data/effects/peds/first_person.meta',
	'data/effects/peds/first_person_alternates.meta',
	'data/effects/peds/mpbattle_overlays.xml',
	'data/effects/explosionfx.dat',
	'data/effects/ptfx.rpf',
	'data/effects/ptfx_hi.rpf',
	'data/effects/ptfx_lo.rpf',
	'data/effects/ptfxassetinfo.meta',
	'data/effects/scriptfx.dat',
	'data/levels/gta5/vehicles.meta',
	'data/carcols.meta',
	'data/carvariations.meta',
	'data/contentunlocks.meta',
	'data/dlctext.meta',
	'data/explosion.meta',
	'data/handling.meta',
	'data/interiorproxies.meta',
	'data/mp_f_freemode_01_mpbattle_shop.meta',
	'data/mp_m_freemode_01_mpbattle_shop.meta',
	'data/mpstatssetup.xml',
	'data/overlayinfo.xml',
	'data/pedalternatevariations.meta',
	'data/pedpersonality.meta',
	'data/peds.meta',
	'data/pickups.meta',
	'data/shop_tattoo.meta',
	'data/shop_vehicle.meta',
	'data/shop_weapon.meta',
	'data/srllist.meta',
	'data/weaponarchetypes.meta',
	'audio/dlcbattle_amp.dat10',
  'audio/dlcbattle_amp.dat10.nametable',
  'audio/dlcbattle_amp.dat10.rel',
  'audio/dlcbattle_game.dat151',
  'audio/dlcbattle_game.dat151.nametable',
  'audio/dlcbattle_game.dat151.rel',
  'audio/dlcbattle_mix.dat15',
  'audio/dlcbattle_mix.dat15.nametable',
  'audio/dlcbattle_mix.dat15.rel',
  'audio/dlcbattle_sounds.dat54',
  'audio/dlcbattle_sounds.dat54.nametable',
  'audio/dlcbattle_sounds.dat54.rel',
  'audio/dlcbattle_speech.dat4',
  'audio/dlcbattle_speech.dat4.nametable',
  'audio/dlcbattle_speech.dat4.rel',
	'audio/sfx/dlc_battle/batfm.awc',
	'audio/sfx/dlc_battle/battle_mix_dj_changeover.awc',
	'audio/sfx/dlc_battle/blimp_promotion_mix1_sample.awc',
	'audio/sfx/dlc_battle/blimp_promotion_mix2_sample.awc',
	'audio/sfx/dlc_battle/blimp_promotion_mix3_sample.awc',
	'audio/sfx/dlc_battle/blimp_promotion_mix4_sample.awc',
	'audio/sfx/dlc_battle/bmad_intro_mastered.awc',
	'audio/sfx/dlc_battle/btl_blmadonna.awc',
	'audio/sfx/dlc_battle/btl_carmine.awc',
	'audio/sfx/dlc_battle/btl_champagne_minigame',
	'audio/sfx/dlc_battle/btl_club_dj_callout_crowd_cheer.awc',
	'audio/sfx/dlc_battle/btl_club_open_transition_crowd.awc',
	'audio/sfx/dlc_battle/btl_connie.awc',
	'audio/sfx/dlc_battle/btl_dave.awc',
	'audio/sfx/dlc_battle/btl_dixon.awc',
	'audio/sfx/dlc_battle/btl_fm_th.awc',
	'audio/sfx/dlc_battle/btl_lazlow.awc',
	'audio/sfx/dlc_battle/btl_marcel.awc',
	'audio/sfx/dlc_battle/btl_mateo.awc',
	'audio/sfx/dlc_battle/btl_solomun.awc',
	'audio/sfx/dlc_battle/btl_tony.awc',
	'audio/sfx/dlc_battle/btl_yohan.awc',
	'audio/sfx/dlc_battle/club_dj_mix_preview_01.awc',
	'audio/sfx/dlc_battle/club_dj_mix_preview_02.awc',
	'audio/sfx/dlc_battle/club_dj_mix_preview_03.awc',
	'audio/sfx/dlc_battle/club_dj_mix_preview_04.awc',
	'audio/sfx/dlc_battle/club_intro_mastered.awc',
	'audio/sfx/dlc_battle/club_intro2_mastered.awc',
	'audio/sfx/dlc_battle/club_open_mastered.awc',
	'audio/sfx/dlc_battle/dixn_intro_mastered.awc',
	'audio/sfx/dlc_battle/dlc_battle_powerplay_bespoke.awc',
	'audio/sfx/dlc_battle/dlc_battle_powerplay_carsteal.awc',
	'audio/sfx/dlc_battle/dlc_battle_powerplay_gotmove.awc',
	'audio/sfx/dlc_battle/dlc_battle_powerplay_popo.awc',
	'audio/sfx/dlc_battle/dlc_battle_powerplay_psycho.awc',
	'audio/sfx/dlc_battle/dlc_btl_cotp_remix_01.awc',
	'audio/sfx/dlc_battle/dlc_btl_hp_remix_01.awc',
	'audio/sfx/dlc_battle/dlc_btl_rb_remix_01.awc',
	'audio/sfx/dlc_battle/dlc_btl_sm_remix_01.awc',
	'audio/sfx/dlc_battle/dlc_btl_tp_remix_01.awc',
	'audio/sfx/dlc_battle/dlc_btl_tp_remix_02.awc',
	'audio/sfx/dlc_battle/dlc_btl_tp_remix_03.awc',
	'audio/sfx/dlc_battle/freecrawler.awc',
	'audio/sfx/dlc_battle/freecrawler_npc.awc',
	'audio/sfx/dlc_battle/jimmyboston.awc',
	'audio/sfx/dlc_battle/kerry.awc',
	'audio/sfx/dlc_battle/lacey.awc',
	'audio/sfx/dlc_battle/lazfm.awc',
	'audio/sfx/dlc_battle/menacer.awc',
	'audio/sfx/dlc_battle/menacer_npc.awc',
	'audio/sfx/dlc_battle/miranda.awc',
	'audio/sfx/dlc_battle/nigel1bcelebmale01.awc',
	'audio/sfx/dlc_battle/oppressor2.awc',
	'audio/sfx/dlc_battle/paifm.awc',
	'audio/sfx/dlc_battle/poppy.awc',
	'audio/sfx/dlc_battle/scramjet.awc',
	'audio/sfx/dlc_battle/scramjet_npc.awc',
	'audio/sfx/dlc_battle/smun_intro_mastered.awc',
	'audio/sfx/dlc_battle/smun_intro2_mastered.awc',
	'audio/sfx/dlc_battle/stafford.awc',
	'audio/sfx/dlc_battle/stafford_npc.awc',
	'audio/sfx/dlc_battle/strikeforce.awc',
	'audio/sfx/dlc_battle/swinger.awc',
	'audio/sfx/dlc_battle/swinger_npc.awc',
	'audio/sfx/dlc_battle/tale_intro_remastered.awc',
	'audio/sfx/dlc_battle/terbyte.awc',
	'audio/sfx/dlc_battle/terbyte_npc.awc',
}

data_file 'VEHICLE_LAYOUTS_FILE' 'data/ai/vehiclelayouts.meta'

data_file 'CLIP_SETS_FILE' 'data/anim/clip_sets/clip_sets.xml'
data_file 'HANDLING_FILE' 'data/handling.meta'
data_file 'VEHICLE_METADATA_FILE' 'data/levels/gta5/vehicles.meta'
data_file 'CARCOLS_FILE' 'data/carcols.meta'
data_file 'VEHICLE_VARIATION_FILE' 'data/carvariations.meta'
data_file 'VEHICLE_SHOP_DLC_FILE' 'data/shop_vehicle.meta'

data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_battle'
data_file 'AUDIO_SYNTHDATA' 'audio/dlcbattle_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audio/dlcbattle_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/dlcbattle_sounds.dat'
data_file 'PED_FIRST_PERSON_ALTERNATE_DATA' 'data/effects/peds/first_person_alternates.meta'

client_script 'names.lua'
